# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, b'Private Message'), (1, b'System Notification')], default=1)),
                ('href', models.TextField(null=True)),
                ('notification', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('read_date', models.DateTimeField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
