# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-31 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_terms_accept_for_existing_users(apps, schema_editor):
    TermsAccept = apps.get_model("terms", "TermsAccept")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    TermsAccept.objects.bulk_create([
        TermsAccept(user=u) for u in User.objects.all()
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_termsconditions_last_updated_on")
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_accept_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_terms_accept_for_existing_users),
    ]
