# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 11:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmifProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')], default=b'registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('paginator', models.IntegerField(choices=[(5, b'5'), (10, b'10'), (25, b'25'), (50, b'50'), (-1, b'All')], default=10, max_length=2)),
                ('search_type', models.CharField(choices=[(b'answers', b'Search on answers'), (b'questions', b'Search on questions'), (b'all', b'Search answers and questions')], default=b'all', max_length=20)),
                ('mail_news', models.BooleanField(default=True)),
                ('mail_not', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete'),
                'abstract': False,
                'permissions': (('view_profile', 'Can view profile'),),
            },
        ),
        migrations.CreateModel(
            name='NavigationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedUserDbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('enabled', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
