# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190319_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emifprofile',
            name='paginator',
            field=models.IntegerField(choices=[(5, b'5'), (10, b'10'), (25, b'25'), (50, b'50'), (-1, b'All')], default=10),
        ),
    ]
