# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190601_1808'),
   ]

    operations = [
        migrations.AddField(
            model_name='termsconditions',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
