# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
