# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='shared',
            field=models.ManyToManyField(related_name='fingerprint_shared_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
