# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20190319_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
