# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20190516_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfields',
            name='view',
            field=models.CharField(choices=[(b'TB', b'Table View'), (b'LT', b'List View'), (b'CD', b'Card View')], default=b'TB', max_length=2),
        ),
    ]
