# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communityfields_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfields',
            name='icon',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='communityfields',
            name='section',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityfields',
            name='show_label',
            field=models.BooleanField(default=False),
        ),
    ]
