# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20190621_1407'),
        ('community', '0006_auto_20190621_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfields',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
    ]
