# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communityfields_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfields',
            name='icon',
            field=models.CharField(default=b'', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='communityfields',
            name='section',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='communityfields',
            name='view',
            field=models.CharField(choices=[(b'TB', b'Table View'), (b'LT', b'List View'), (b'CD', b'Card View')], default=b'TB', max_length=2, null=True),
        ),
    ]
