# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20190627_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfields',
            name='show_label',
            field=models.NullBooleanField(default=False),
        ),
    ]
