# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20190627_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityJoinForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityJoinFormReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('commuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.CommunityUser')),
                ('join_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.CommunityJoinForm')),
            ],
        ),
    ]
