# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_communityjoinform_communityjoinformreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='query',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
