# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-26 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_community_query'),
        ('community', '0011_auto_20201204_1731'),
    ]

    operations = [
    ]
