# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-26 10:57
from __future__ import unicode_literals

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0012_merge_20210426_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitiesFavorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('sortid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=community.models.iconThumbnail)),
                ('outbound_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='header_display',
            field=models.CharField(choices=[(b'none', b'Do not display'), (b'comm', b'Community logo'), (b'ques', b'Questionnaire logos'), (b'both', b'Community and questionnaire logos')], default=b'none', max_length=4),
        ),
        migrations.AddField(
            model_name='community',
            name='landpage_url',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='communitiesfavorited',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AddField(
            model_name='communitiesfavorited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
