# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20201127_1436'),
        ('community', '0013_auto_20210426_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityExcludedExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[(b'TB', b'Table View'), (b'LT', b'List View'), (b'CD', b'Card View')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
        ),
    ]
