# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-20 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_communityexcludedextrafields'),
        ('community', '0014_communityjoinform_required'),
    ]

    operations = [
    ]
