# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20210910_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfields',
            name='apply_formatting',
            field=models.BooleanField(default=True),
        ),
    ]
