# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-22 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0019_communityfields_apply_formatting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityuser',
            unique_together={('community', 'user')},
        ),
    ]
