# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-15 18:17
from __future__ import unicode_literals

import community.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20220222_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 200], upload_to=community.models.iconHash),
        ),
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 200], upload_to=community.models.iconThumbnail),
        ),
        migrations.AlterField(
            model_name='externalcommunity',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 200], upload_to=community.models.iconThumbnail),
        ),
    ]
