# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-23 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fill_new_fields(apps, schema_editor):
    CommunityActivation = apps.get_model("community", "CommunityActivation")

    for ca in CommunityActivation.objects.all():
        ca.community = ca.commuser.community
        ca.user = ca.commuser.user
        ca.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0021_auto_20220215_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivation',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AddField(
            model_name='communityactivation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(  # set on_delete to SET_NULL
            model_name='communityactivation',
            name='commuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.CommunityUser'),
        ),
        migrations.RunPython(fill_new_fields),
        migrations.AlterField(  # remove null=True
            model_name='communityactivation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AlterField(  # remove null=True
            model_name='communityactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.CreateModel(
            name='CommunityActivationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
        migrations.AddField(
            model_name='communityactivation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='communityactivation',
            name='msg2user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.CommunityActivationMessage'),
        ),
        migrations.AddField(
            model_name='communityactivation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='communityactivationmessage',
            unique_together={('community', 'message')},
        ),

        migrations.AlterField(  # added rejected status
            model_name='communityuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Waiting approval in community'), (1, b'Enabled in community'), (2, b'Enabled, but with restricted access to certain databases'), (3, b'Blocked by community owner'), (4, b'Not accepted into the community')], default=0),
        ),
    ]
