# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_community_questionnaires_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Waiting approval in community'), (1, b'Enabled in community'), (2, b'Enabled, but with restricted access to certain databases'), (3, b'Blocked by community owner'), (4, b'Not accepted into the community'), (5, b'Removed from the community')], default=0),
        ),
    ]
