# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190319_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='type',
            field=models.IntegerField(choices=[(0, b'Global plugin, for the main dashboard'), (1, b'Database related plugin, for the database view'), (3, b'Full-fledged application widget'), (2, b'Third party full-fledged applications'), (5, b'Clickable link that shows in the sidebar')], default=0),
        ),
    ]
