# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_plugin_use_thirdparty_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='use_thirdparty_iframe',
        ),
        migrations.AddField(
            model_name='plugin',
            name='plugin_view',
            field=models.IntegerField(choices=[(0, b'Use the Default IFrame from HTML'), (1, b'Use the Third Party IFrame'), (2, b'Use as Link to Webpage')], default=0),
        ),
    ]
