# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_auto_20201206_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='type',
            field=models.IntegerField(choices=[(0, b'Global plugin, for the main dashboard'), (1, b'Database related plugin, for the database view'), (3, b'Full-fledged application widget'), (2, b'Third party full-fledged applications')], default=0),
        ),
    ]
