# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-15 18:17
from __future__ import unicode_literals

import developer.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_merge_20210520_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to=developer.models.iconHash),
        ),
    ]
