# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='in_preview',
            field=models.BooleanField(default=False),
        ),
    ]
