# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnareimportfile',
            name='error_message',
            field=models.TextField(help_text=b'None if the import succeeded with status FINISHED. An error message if it failed with status ABORTED.', null=True),
        ),
    ]
