# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
        ('questionnaire', '0002_questionnaire_in_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='preview_fingerprint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_questionnaire', to='fingerprint.Fingerprint'),
        ),
        migrations.AddField(
            model_name='questionnareimportfile',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
    ]
