# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190514_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='logo',
            field=models.ImageField(default=b'', upload_to=questionnaire.models.questionnaire_logo_directory_path),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
