# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190409_1138'),
        ('questionnaire', '0002_questionnareimportfile_error_message'),
    ]

    operations = [
    ]
