# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_merge_20190513_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnareimportfile',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnareimportfile',
            name='status',
            field=models.IntegerField(choices=[(0, b'Questionnaire import started'), (1, b'Questionnaire is being imported'), (2, b'Questionnaire finished importing'), (3, b'Questionnaire import aborted'), (4, b'Questionnaire is currently in preview')], default=0),
        ),
    ]
