# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20190513_1103'),
        ('questionnaire', '0005_auto_20190516_1534'),
    ]

    operations = [
    ]
