# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20190601_1808'),
        ('questionnaire', '0006_merge_20190522_1024'),
    ]

    operations = [
    ]
