# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20190621_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='location',
        ),
    ]
