# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-13 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_remove_questionnaire_location'),
        ('questionnaire', '0007_auto_20190715_1122'),
    ]

    operations = [
    ]
